import React from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import { GetStaticProps } from 'next'
import Nav from '../components/Nav/Nav.js'
import styles from '../styles/home.module.css'
import Banner from '../components/Banner/Banner.js'
import Container from '../components/Container/Container.js'
import {
  ApiCallout,
  Callout,
  uiCallouts,
  apiUrl,
} from '../lib/callouts'

const CalloutsSection: React.FC<{ callouts: Array<Callout> }> = ({ callouts }) => {
  return (
    <section className={styles.callouts}>
      <Container>
        <h2 className={styles.stepH2}>How It Works</h2>
        <div className={styles.steps}>
          {callouts.map((callout, index) => {
            return (
              <div key={'callout-' + index} className={styles.step}>
                <h1 className={styles.stepH1}>
                  {`0${index + 1}`}
                </h1>
                <p className={styles.stepLead}>{callout.title}</p>
                <div className={styles.stepBody}>
                  <p className={styles.stepP}>{callout.body}</p>
                </div>
              </div>
            )
          })}
        </div>
      </Container>
    </section>
  );
}

const Home: NextPage<{callouts: Array<Callout>}> = ({ callouts }) => {
  return (
    <>
      <Head>
        <title>SingleStone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet"/ >
      </Head>
      <Nav />
      <main>
        <Banner />
        <CalloutsSection callouts={callouts} />
      </main>
    </>
  )
}


export const getStaticProps: GetStaticProps = async () => {
  const apiCallouts: Array<ApiCallout> = await (fetch(apiUrl)).then(res => res.json());
  return {
    props: {
      callouts: uiCallouts(apiCallouts)
    }
  }
}

export default Home
