import React from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import { GetServerSideProps } from 'next'
import Nav from '../components/Nav/Nav.js'
import styles from '../styles/home.module.css'
import Button from '../components/Button/Button.js'
import Container from '../components/Container/Container.js'
import {
  ApiCallout,
  Callout,
  uiCallouts,
  apiUrl,
} from '../lib/callouts'

const BannerSection = () => {
  return (
    <section className={styles.banner}>
      <Container>
        <div className={styles.bannerContent}>
          <h3>New Games and Accessories</h3>
          <div className="sy1">
            <h1>Monthly packages.</h1>
            <h1>Excitement delivered daily.</h1>
          </div>
          <p style={{maxWidth: '450px'}}>What's the best way to shop for the latest video games and peripherals? How about never shopping at all? You'll get new stuff on your doorstep &mdash; every month.</p>
          <div className="sy1">
            <Button type="button">get started</Button>
          </div>
        </div>
      </Container>
    </section>
  );
};

const CalloutsSection: React.FC<{ callouts: Array<Callout> }> = ({ callouts }) => {
  return (
    <section className={styles.callouts}>
      <Container>
        <h2 className={styles.stepH2}>How It Works</h2>
        <div className={styles.steps}>
          {callouts.map((callout, index) => {
            return (
              <div className={styles.step}>
                <h1 className={styles.stepH1}>
                  {`0${index + 1}`}
                </h1>
                <p className={styles.stepLead}>{callout.title}</p>
                <div className={styles.stepBody}>
                  <p className={styles.stepP}>{callout.body}</p>
                </div>
              </div>
            )
          })}
        </div>
      </Container>
    </section>
  );
}

const Home: NextPage<{callouts: Array<Callout>}> = ({ callouts }) => {
  return (
    <>
      <Head>
        <title>SingleStone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <BannerSection />
        <CalloutsSection callouts={callouts} />
      </main>
    </>
  )
}


export const getServerSideProps: GetServerSideProps = async () => {
  const apiCallouts: Array<ApiCallout> = await (fetch(apiUrl)).then(res => res.json());
  return {
    props: {
      callouts: uiCallouts(apiCallouts)
    }
  }
}

export default Home
